name: Bug Report
description: Report a bug with Super Mario Bros. Remastered
title: '[Bug Report]: '

body:
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "Specify the version of the game you used when you encountered the bug. You can find the game version at the bottom-left of the title screen."

  - type: checkboxes
    id: bug_type
    attributes:
      label: "Bug Type"
      description: "Select all that apply (leave blank if unsure)."
      options:
        - label: campaign bug
        - label: editor bug
        - label: custom pack bug
        - label: ui bug
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please write a clear and concise description of the bug."
      
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Reproduction Steps"
      description: "Please list the steps taken to reproduce the bug, e.g. 1. Go to ... 2. Do ..."
      
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain the bug."
      
labels:
  - ${{ values.bug_type }}